# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89232363a24a95992d02e7be6c256fb8da03ea104b2c185c1cdc3c8bc97325f033ea077802060da13667c71f9f3fec17b602c2e1b62bf17d71de65285e65b855

test:
  secret_key_base: e82f33b3572ef186f2b1bed5f2487c413695d862843c5a2bb0c5db811ce699b518ad20f2e304634c2a02c85f15366540f5c9782e91c9467610c8c4f29b1afc9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
